### ISSUE TITLE
Screenshot link dead

### ISSUE THREAD

**Issue by apennebaker-ni** [sickill/vim-monokai#13]
The screenshot link on the README is dead.

**Comment by indiesquidge** [comment]
Yeah, strange. When I take the _exact_ code and post it to a `.markdown` file, it works fine.

**Comment by apennebaker-ni** [comment]
I had to fix the screenshot in one of my README's. Perhaps GitHub changed the URL syntax?

https://github.com/mcandre/moss#examples

**Comment by sickill** [comment]
This is weird. When you click on the link to screenshot it opens correctly...
