### ISSUE TITLE
Higlighting for whitespaces and newlines is wrong

### ISSUE THREAD

**Issue by ghost** [sickill/vim-monokai#20]
![screenshot_2016-03-06_23-25-51](https://cloud.githubusercontent.com/assets/10116666/13556769/087c038c-e3f3-11e5-8b5b-8d5bd0f7426e.png)
The background for these characters should be the same as for letters.

**Comment by mkli90** [comment]
This seems to be an issue with your shell. Can't recreate this with a default "Konsole" under Kubuntu 16.04.1. See picture below:

![screenshot_20160922_115429](https://cloud.githubusercontent.com/assets/8678523/18743889/7893e3fa-80bb-11e6-9035-a4344de264a6.png)

**Comment by ingram1107** [comment]
Cannot replicate this, closing
