### ISSUE TITLE
Some question about font

### ISSUE THREAD

**Issue by LikiPiki** [sickill/vim-monokai#23]
What font you use in the screenshot?
https://camo.githubusercontent.com/66d46739895bdea648a10e286a6381943f876d04/68747470733a2f2f636c6f75642e6769746875622e636f6d2f646f776e6c6f6164732f7369636b696c6c2f76696d2d6d6f6e6f6b61692f76696d2d6d6f6e6f6b61692e706e67

**Comment by sickill** [comment]
Hmm, I'm not sure, it was long time ago, but I suspect it might have been Droid Sans Mono.

**Comment by LikiPiki** [comment]
thanks
