### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by louispan** [sickill/vim-monokai#24]
Hi sickill,

I would like to use a color scheme based on yours. Would you be able to provide a license e.g. [BSD-2-Cluase](https://opensource.org/licenses/BSD-2-Clause) or [MIT](https://opensource.org/licenses/MIT), so that I may fork your github repo properly?

**Comment by louispan** [comment]
I noticed that https://github.com/sickill/vim-monokai/blob/master/colors/monokai.vim has a comment `Converted from Textmate theme Monokai using Coloration v0.3.2 (http://github.com/sickill/coloration)`
and that `coloration` has a license https://github.com/sickill/coloration/blob/master/LICENSE.txt

Could you use the same license for this repo?

**Comment by sickill** [comment]
Added license file.

**Comment by louispan** [comment]
Thank you for the quick response!
