### ISSUE TITLE
don't work : (

### ISSUE THREAD

**Issue by RanchoCooper** [sickill/vim-monokai#27]
I did according to the `Installation`
but the theme remains old style

**Comment by mkli90** [comment]
Did you copy the monokai.vim file into your ~/.vim/colors folder? You need to place it there and then set the settings according to the instructions. Worked like a charm for me. :)

**Comment by j16180339887** [comment]
You have to remove all the other vimrcs, just type

`:version`

and vim will show how many vimrcs did it just load.

**Comment by HmzAli** [comment]
Too late to the party :P, but just in case someone is facing the same issue. Make sure that vimrc is installed on your machine first before setting up the theme.

**Comment by RanchoCooper** [comment]
thanks, it works and I'll close this issue
