### ISSUE TITLE
I want to modify comment color, what should i do?

### ISSUE THREAD

**Issue by ghost** [sickill/vim-monokai#38]
![](http://hololenspic.oss-cn-shenzhen.aliyuncs.com/18-7-1/55610995.jpg)

first line, my comment color not good, help me.

**Comment by arvind-iyer** [comment]
You would have to add a line similar to the following in your vimrc. This line would make the comments appear as a deep blue colour. 
```vim
hi Comment ctermfg=31 guifg=#0087af 
```
Replace the values for ctermfg and guifg with whatever colour you would prefer. Use [this site](http://vim.wikia.com/wiki/Xterm256_color_names_for_console_Vim) for reference if you are not familiar with how the codes represent colours.

**Comment by ingram1107** [comment]
close the issue if you solved your problem
