### ISSUE TITLE
How to modify the color of object attributes in monokai-color-theme.json

### ISSUE THREAD

**Issue by lovelyJason** [sickill/vim-monokai#42]
What I use is vscode.I want to know how to change  the color of object attribute.I tried many  times without result.
![Snipaste_2019-08-23_13-52-54](https://user-images.githubusercontent.com/50656459/63569946-fca1ff80-c5ad-11e9-9b64-89eb6bdf5b8c.png)

**Comment by sickill** [comment]
This project provides color scheme for Vim editor, not VS Code, sorry.
