### ISSUE TITLE
Highlighting of a c-like for loop in bash

### ISSUE THREAD

**Issue by h4k1m0u** [sickill/vim-monokai#45]
The highlighting of c-like for loops in bash isn't working as you can see on the screenshot below, where only the '0' has a different color than the whole for line.

![vim](https://user-images.githubusercontent.com/4227512/81797836-90867380-950f-11ea-87de-61693da19082.png)

**Comment by ingram1107** [comment]
I have modified it a bit, here's the result:

![new](https://user-images.githubusercontent.com/51374700/152124982-ec58daa3-4b2b-4bf6-9cdb-b189e1461497.png)

Is this more akin to your liking?

**Comment by h4k1m0u** [comment]
Yeah, thanks a lot, it looks cooler than before.
