### ISSUE TITLE
how to modify the background color?

### ISSUE THREAD

**Issue by juliozaravia** [sickill/vim-monokai#46]
Hello everyone! I am new to using vim, however it has proven to be a very effective tool. I've googled but can't find a way to change the background color assigned by the Monokai theme. I have seen the following in the code:

`
set background=dark
`

However I have tried to edit that line without success (in addition to other recommendations on google).

In short, I would like to know how I can change the "gray" background color assigned by the Monokai.vim theme to a darker one (something like # 222222). 

Hope you can give me some idea.

**Comment by cbracketdash** [comment]
I have the same question. Did you find an answer?

**Comment by hugoruscitti** [comment]
Hi!, just add this line to the bottom on your .vimrc file:

```
hi Normal ctermfg=231 ctermbg=235 cterm=NONE guifg=#f8f8f2 guibg=#222222 gui=NONE
```

or press ":" and paste the same line to try different values without leave the editor:

```
hi Normal ctermfg=231 ctermbg=235 cterm=NONE guifg=#f8f8f2 guibg=#222222 gui=NONE
```

The new color is in the `guibg` variable.
