### ISSUE TITLE
How can I install this theme in NeoVim ?

### ISSUE THREAD

**Issue by sajusat** [sickill/vim-monokai#47]
Hi,
  Can someone tell me how to install this theme in NeoVim ?

regards

**Comment by nicolasdanelon** [comment]
this is not the place to ask for that. please try with [google](https://vi.stackexchange.com/questions/14587/which-directory-to-put-color-schemes/18279) or [youtube](https://www.youtube.com/watch?v=Ow03haHO1NE) and close this issue
