### ISSUE TITLE
Can I help out as a maintainer?

### ISSUE THREAD

**Issue by LilyReile** [sickill/vim-monokai#49]
Hey, I noticed this hasn't been updated in awhile and there are some outstanding issues and PRs I'd like to see merged.

I like this color scheme a lot, so would be happy to help maintain this repo. One thing I'd want to do is make this compatible with vim-plug for easy installation.

**Comment by dave-kennedy** [comment]
I've been looking for an actively maintained fork to submit a pull request to. [This one](https://github.com/ingram1107/vim-monokai) looked pretty good but so far it's been crickets.

**Comment by sickill** [comment]
@DylanReile hey! Sorry for late reaction. This sounds good. I don't use this theme nor vim much these days, so it makes sense for someone to take over. Granting you maintainer rights now.

**Comment by dave-kennedy** [comment]
@DylanReile now that you're a maintainer, and @ingram1107 woke up from the dead, can you merge some of these PRs? I'm particularly interested in #48 :)

**Comment by ingram1107** [comment]
I am waiting for this project to be active again. In the meantime, I'm maintaining [another fork](https://github.com/ingram1107/moneokai)  from the main repo so that I could keep the pull request #48 clean.

**Comment by sickill** [comment]
Not sure if @DylanReile is still interested in taking over.

Would you like to step in @ingram1107 ? Happy to make you a maintainer if that works for you.

**Comment by DylanReile** [comment]
I think @ingram1107 would be a better maintainer. I use this colorscheme every day, but somehow it gets pushed to the back of the priority list. 🤷

**Comment by ingram1107** [comment]
I'm currently experimenting another colorscheme and since then I've not working too much on to the fork that I've created. However, I would be glad to help a bit.

**Comment by kstevens715** [comment]
@sickill First, thank you for this color scheme. I’ve been using it for almost 9 years now. Every time I try another theme I end up coming back to this one.

I’d love to help out maintaining it. One thing I’m interested in is seeing if it could add better support for vim-treesitter.

**Comment by LilyReile** [comment]
@ingram1107 Do you mind if I ask what colorscheme you're using now?

**Comment by ingram1107** [comment]
@LilyReile I am using [this monokai colorscheme](https://www.github.com/tanvirtin/monokai.nvim).

**Comment by LilyReile** [comment]
@ingram1107 Ty. Does that work with regular old terminal vim or only with neovim?

**Comment by dave-kennedy** [comment]
FWIW I really like this one: https://github.com/crusoexia/vim-monokai
