### ISSUE TITLE
how to set background transparent? im using windows

### ISSUE THREAD

**Issue by WellingtonNico** [sickill/vim-monokai#54]
im not able to change the background

**Comment by ingram1107** [comment]
try `hi Normal guifg=NONE guibg=NONE`

**Comment by WellingtonNico** [comment]
I already did it, didnt work! Im using windows terminal, if it helps..

**Comment by ingram1107** [comment]
Ok, there are several information that you need to provide:

1. Is your terminal set to be transparent?
2. Is it just nvim that has this problem?
3. Do other colorschemes have this issue too?

**Comment by WellingtonNico** [comment]
there was a problem with windows terminal.
